### ISSUE TITLE
Make ETag generation FIPS compliant

### ISSUE THREAD

**Issue by plembke** [tpeczek/Lib.Web.Mvc#101]
the use of the MD5 Crypto service in RangeFileResult.GenerateEntityTag is not FIPS compliant.  Please change the MD5 to a SHA1CryptoServiceProvider.

**Comment by tpeczek** [comment]
I'm not sure if ETag generation has to be FIPS compliant, after all this is not encryption or something which deals with sensitive data. The only goal is getting unique value.

Is this coming from some static code scan which you need to pass?

**Comment by neggen-igx** [comment]
Yes, this is failing the built-in windows FIPS check when you have that mode set in the OS level. Would be great to change for me too.

**Comment by tpeczek** [comment]
In such case I would be considering a non-crypto based ETag generation, for example:

    long enityTagHash = FileModificationDate.ToFileTime() ^ FileLength;
    return Convert.ToString(enityTagHash, 16);

Which is similar to what ASP.NET Core is doing in Static Files Middleware. This will have positive impact on performance as being lighter from MD5 (while SHA1 would be heavier).

The question is can this be parameterized. My concern is backward compatibility. If the ETag generation will be changed it will result in incorrect handling of If-Match and If-None-Match as they will contain ETag generated with old algorithm.

**Comment by neggen-igx** [comment]
The .NET CORE approach seems ok to me, but the backwards compatibility is a good consideration. For me it is not failing FIPS check at a code static analysis level - just run-time - so a parametrization would work - but some people are going to have a static analysis failure over this I would image. 

It seems like changing to the .NET Core style method or SHA1 would break the backwards compatibility either way right?

**Comment by tpeczek** [comment]
Yes, which hashing algorithm to use and how to handle backwards compatibility are two separated aspects.

**Comment by neggen-igx** [comment]
Ok, got it. An override on the RangeFileResult with a encoding parameter would be great. The internal branching would on your implementation would be clearly visible so in a static analysis review they would see it would never fire the MD5 branch in FIPS mode if that did become an issue. And if it still defaults to MD5 then it won't break anyone who doesn't care about FIPS. I don't know how to get FIPS status at run time except a reg key read which is pretty heavy handed, but there is also the override setting that may be in play on a given site: https://msdn.microsoft.com/en-us/library/hh202806(v=vs.110).aspx

**Comment by tpeczek** [comment]
The only bulletproof way of runtime protection I know of in this case is try-catching the MD5 usage which I'm going to do and in such case use the new mode. Also based on InvalidOperationException occurence I will switch the default for next instances in order to avoid constant exceptions to handle (performance).

In general scheduling for v6.8.1
The only bulletproof way of runtime protection I know of in this case is try-catching the MD5 usage which I'm going to do and in such case use the new mode. Also based on InvalidOperationException occurence I will switch the default for next instances in order to avoid constant exceptions to handle (performance).

In general scheduling for v6.8.1

**Comment by neggen-igx** [comment]
Thank you Thomas - this sounds excellent! Appreciate the speedy and detailed analysis. Will keep an eye out for 6.8.1.

**Comment by tpeczek** [comment]
The changes are in if somebody wishes to do some "acceptance testing" based on source code ;)

**Comment by neggen-igx** [comment]
We ran into some trouble testing this because our installed software targets .NET 4.5.2. We have been on Lib.Web.Mvc 6.7.0 for a while, but upon trying the release of 6.8.0 I see that there is no longer a .NET 4.5.2 package published for v6.8.0. 

We were able to manually build a local debug copy of 6.7.0 with the same changes you did for this FIPS update and it works great on our FIPS test environment so your code looks perfect. Great job on it!

However, since Lib.Web.Mvc 6.8.x won't work without .NET 4.6.x I'm stuck in being able to roll out a fix to production.  I have a large installed based of installed software using your library and can't make all those servers switch to .NET 4.6.x all at once. 

Would it be possible to have either a Lib.Web.Mvc 6.8.x that also works with .NET 4.5.2 or if its easier maybe a Lib.Web.Mvc 6.7.x package with the same FIPS change?

**Comment by tpeczek** [comment]
The v6.8.x is dependent on HTTP/2 functionality present in .NET 4.6.x.

Making a separated v6.7.x branch should be doable and would be a correct way to go here - that involves some extra effort but maybe I'll still be able to do it in March timeline.

**Comment by neggen-igx** [comment]
Thank you so much for being willing to make a 6.7.x branch for this.

**Comment by tpeczek** [comment]
@neggen-igx You know that I accept donations, right? :wink:

I've created [v6.7.x branch](https://github.com/tpeczek/Lib.Web.Mvc/tree/v6.7.x) and applied changes there. I should be able to release both v6.7.1 and v6.8.1 by Monday.

**Comment by neggen-igx** [comment]
One of my colleagues tested 6.7.1 out and it works great! Thank you! We will wait for 6.7.1 release to Nuget. 

Would be happy to donate some money. Do you have a Paypal link?

**Comment by tpeczek** [comment]
Couple days ago I've set up a [pledgie camping](https://pledgie.com/campaigns/33546) for this project - it is powered by PayPal.

**Comment by neggen-igx** [comment]
Alright - I donated. Do you think it will publish this week still maybe? Or not till next?

**Comment by tpeczek** [comment]
Thank you, to be honest I wasn't expecting anybody will (I still believe you might be the first and last person to do so).

As you guys seem to be using this for some real business I've decided to skip some sleep and publish v6.7.1 today, v6.8.1 will follow on weekend.
